export const GET_EDITORS = 'GET_EDITORS';
export const ADD_EDITOR = 'ADD_EDITOR';
export const DELETE_EDITOR = 'DELETE_EDITOR';
export const EDITORS_LOADING = 'EDITORS_LOADING';

export const GET_COTTAGES = 'GET_COTTAGES';
export const ADD_COTTAGE = 'ADD_COTTAGE';
export const DELETE_COTTAGE = 'DELETE_COTTAGE';
export const COTTAGES_LOADING = 'COTTAGES_LOADING';

export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const EDIT_RESERVATION_STATUS = 'EDIT_RESERVATION_STATUS';
export const RESERVATIONS_LOADING = 'RESERVATIONS_LOADING';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const EDIT_EDITOR_STATUS = 'EDIT_EDITOR_STATUS';
